### ISSUE TITLE
Screen Jank - Started last Week

### ISSUE THREAD

**Issue by GJH0771** [benfl3713/DepartureBoard#221]
The screen has started to Jank on an Android Tablet

When opening a single board destination on my Android Tablet, it has started to Jank by increasing amounts of equal time.  (4 secs stall, then 4 sec scroll, 8 second stall and then 8 second scroll.  It continues to do this until eventually it just stalls and updates for a stutter second)

Up until last week it never used to do this.  I also have an equivalent Android Tablet and it has started doing the same on this one.

I have run the same destination (and others) on iOS but do not witness a similar problem.

Finally, apologies to all - I am a complete newbie to Android.

**Comment by benfl3713** [comment]
Hi @GJH0771 

I released a new feature last week so I'll take a look at the change to see If I can see why you're seeing this issue
I'll get back to you once I have done my investigation

Cheers
Ben

**Comment by GJH0771** [comment]
Thanks Ben

**Comment by ben-fletcher** [comment]
Hello again @GJH0771 

I have deployed an old version of the website to the following url:
https://beta--leddepartureboardcom.netlify.app/singleboard/EUS

Can you please confirm that when using this link, the screen jank issue goes away

Cheers
Ben

**Comment by GJH0771** [comment]
Ben

The link works a treat - does that narrow down the issue for you?

Thanks for taking the time to look at this and for such a swift response - much appreciated.

Cheers

Gordon

**Comment by benfl3713** [comment]
Hi @GJH0771 

I have made the decision to completely rebuild the singleboard feature as it was written over a year ago and needs tidying up anyway. This will take a couple of days so for now I shall leave that link I sent you online so that you can use that whilst I rebuilt the singleboard. I'll let you know once the work is complete

Cheers
Ben

**Comment by GJH0771** [comment]
Thanks for the update Ben - much appreciated

**Comment by benfl3713** [comment]
Hi @GJH0771 

I have done a re-write of the singleboard functionity and have generated a deploy preview.
As I was unable to re-create your issue I don't know if this will fix you problem or not.
Can you go to the following preview link and confirm if the issue is fixed or not.
https://deploy-preview-223--leddepartureboardcom.netlify.app/singleboard/BHM

Thanks
Ben

**Comment by GJH0771** [comment]
Ben

Many thanks - whilst certainly better, the Jank remains.  This time I have uninterrupted scrolling for 13 seconds and then a 3 second freeze.  I'll leave this running all day, to see if it gets worse (it did with the previous version) and report back.

Thanks again

Gordon

**Comment by ben-fletcher** [comment]
Hi @GJH0771 

Thanks for the quick response. I have a few other ideas to try. I'd like to confirm whether the jank you're on about is specifically for the row that scrolls along, or whether it's the entire screen? 
Secondly have you attempted to use a different browser on your tablet (I have tested it on my own tablet using google chrome and it works fine). 
Also what brand is your tablet?, So I can try create an environment similar to what your tablet is.

I shall continue to investigate the issue and have multiple different ideas to try
Cheers
Ben

**Comment by GJH0771** [comment]
Hi Ben

I've tried with both Google Chrome and Microsoft Edge - same issue with both browsers.  I purchased the tablet from Amazon - details below.

The scrolling and digital clock both stall for a period of time; seemingly an increasing longer stall, the longer the screen remains active.  My uneducated guess would suggest it may have something to do with the CPU switching between frequencies (??) or a RAM issue due to code?  Interestingly, the latest link you sent doesn't suffer as long a stall duration as the first update you did when this all started.  It does however continue to increase its stall duration the longer the screen is active.

Hope this helps?

Brand	‎Haehne
Package Dimensions	‎33.78 x 19.56 x 4.57 cm; 960 Grams
Batteries	‎1 Lithium ion batteries required. (included)
Item model number	‎MY-PC-ZL80-Black
Manufacturer	‎Haehne
Color	‎Black
Standing screen display size	‎10.1 Inches
Screen Resolution	‎1280 x 800 pixels
Processor Brand	‎AMD
Processor Type	‎ARM 7100
Processor Speed	‎1.3 GHz
Processor Count	‎4
RAM Size	‎2 GB
Computer Memory Type	‎DDR3 SDRAM
Hard Drive Size	‎32 GB
Hard Drive Interface	‎USB
Connectivity Type	‎Cellular, Bluetooth, Wi-Fi
Wireless Type	‎802.11b
Voltage	‎3.7 Volts
Power Source	‎AC & Battery
Hardware Platform	‎Linux
Operating System	‎Android
Are Batteries Included	‎Yes
Lithium Battery Packaging	‎Batteries contained in equipment
Lithium Battery Voltage	‎3.7 Volts
Item Weight	‎960 g
Many thanks again for taking the time to look/resolve.

Kind regards

Gordon

**Comment by GJH0771** [comment]
PS the Beta version continues to work without issue.

**Comment by benfl3713** [comment]
Hi @GJH0771 

I have made some further changes to roll back some changes I made in the last couple of months.
Would you be able to check if this URL works?
https://60e8b166b9b6b50009b32a09--leddepartureboardcom.netlify.app/singleboard/BHM

Thanks for the patience
Ben

**Comment by GJH0771** [comment]
Hi Ben

Apologies for the delay - still no better; possibly slightly worse.  Are you happy I continue to use the beta link you sent the other week?  This continues to work without hiccup.

Gordon

**Comment by benfl3713** [comment]
Hi @GJH0771 

It is fine to use the beta link for as long as you like.

I have made some further changes and would like to see if the issue is now fixed. 
Could you please try the following URL: 
https://60f6f6df4c292e00079323a0--leddepartureboardcom.netlify.app/singleboard/BHM

Thanks for the patience
Ben (leddepartureboard.com)

**Comment by GJH0771** [comment]
Ben

I've sent a reply via Maildrop as it contains a video file (96Meg).  Issue still not resolved, however I thought the video may help?

Apologies for the delay - been away from the office.

Thanks for your persistence.

Gordon

**Comment by GJH0771** [comment]
Attachment available until 24 Aug 2021
Ben

Apologies for the delay - still not fixed.

I've attached a video of the issue if that helps in anyway?  Note the time and scroll stall at two second intervals.  This progressively gets worse the longer the board is running.

Thanks again for your persistence.

Gordon

Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAbUctewdbwWKZkOiDGD63zyMQU1SAchQb9nsfoJQ4XaNltw_dissOvTi%2F%24%7Bf%7D%3Fo%3DArMeAwz2VsS77s1dhYRdWlEAonrwBnycmQtsUaUMq7h5%26v%3D1%26x%3D3%26a%3DCAogxD_kzf3ezwZ_ju4eWDl-5L16dTr1KBPLdACvdUzDwUYSdBCp98znrS8YqYfIu7cvIgEAKgkC6AMA_1n-OE9SBIxBTVJaBCw69OJqJGieDU5C87E4U-e5Hhob6EfzBlrLO3OBMruHTa7TdBfV-BNPp3IkuQwalD7lCbAEVtmAb_CkVxRGSpk---p8R9qDvEtcWZ5PgX0v%26e%3D1629796565%26fl%3D%26r%3D12CB73F2-1F18-454D-9957-8FA61BE8D2F1-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D5B146982-9A84-4EE8-AB11-170D2F212272%26p%3D53%26s%3DkWDUfYVwaPq0vrzXetkwM3iGV0U&uk=sFGernQZ97-Wvl4eG6gCeA&f=IMG_0086.MOV.zip&sz=99546243>IMG_0086.MOV.zip
99.5 MB

**Comment by benfl3713** [comment]
Hi Gordon

Sorry I have not replied for ages.

I have tried a lot of different things and found no solution unfortunately. 
The only thing I can put it down to is the particular hardware you're using.
Sorry to disappoint but I don't think I'll ever solve this issue.

Thanks for Understanding
Ben

**Comment by GJH0771** [comment]
Ben

Really appreciate your efforts in attempting to resolve this. Do you have any objections if I continue to use the Beta version - it works great!!

Kind regards and a Happy New Year

Gordon

**Comment by benfl3713** [comment]
Hi Gordon

Yes it is fine to keep using that version as it costs me nothing to run.
I am also re-designing the website at the moment, so when I have complete that I might ask you to see if it magically fixes your problem

Thanks and Happy New Year
Ben

**Comment by benfl3713** [comment]
Hi again Gordon

Bit of a long shot here, but I am currently doing a redesign and removed a lot of stuff that was introduced that may of caused your issue. Could you please see if this link works for you or whether the issue still remains. Also you get a sneak preview of the new design (Work in progress)

https://deploy-preview-240--leddepartureboardcom.netlify.app/

Cheers
Ben (leddepartureboard)
